name: Laravel CI/CD (MySQL)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laracicd
          MYSQL_USER: polindra
          MYSQL_PASSWORD: polindra
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -p$$MYSQL_ROOT_PASSWORD"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP (8.2.12)
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2.12'
        extensions: mbstring, ctype, fileinfo, openssl, pdo_mysql
        coverage: none

    - name: Install dependencies
      run: composer install --prefer-dist --no-interaction --no-progress

    - name: Configure Laravel .env
      run: |
        cp .env.example .env
        sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=mysql/' .env
        sed -i 's/DB_HOST=.*/DB_HOST=127.0.0.1/' .env
        sed -i 's/DB_PORT=.*/DB_PORT=3306/' .env
        sed -i 's/DB_DATABASE=.*/DB_DATABASE=laracicd/' .env
        sed -i 's/DB_USERNAME=.*/DB_USERNAME=polindra/' .env
        sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=polindra/' .env

    - name: Generate Laravel App Key
      run: php artisan key:generate

    - name: Wait for MySQL to be ready
      run: |
        for i in {1..10}; do
          if mysqladmin ping -h127.0.0.1 -upolindra -ppolindra --silent; then
            echo "MySQL is ready!"
            break
          fi
          echo "Waiting for MySQL... Attempt $i/10"
          sleep 3
        done

    - name: Run Migrations and Seeder
      run: php artisan migrate:fresh --seed

    - name: Run Laravel Tests
      run: php artisan test

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: laravel-app
        path: |
          .
          !vendor/
          !node_modules/
          !.git/
          !.github/
          !storage/debugbar/
        retention-days: 1

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: laravel-app
        path: ./deploy

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        port: 64000

    - name: Deploy via SCP/SSH
      run: |
        ssh -o StrictHostKeyChecking=no -p 64000 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "mkdir -p ~/D4RPL2C-kelompok9-deploy"

        scp -o StrictHostKeyChecking=no -P 64000 -r ./deploy/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/D4RPL2C-kelompok9-deploy/

        ssh -o StrictHostKeyChecking=no -p 64000 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd ~/D4RPL2C-kelompok9-deploy

          # Optional backup
          # sudo tar -czf /backup/laravel-$(date +%F-%H-%M).tar.gz /var/www/D4RPL2C-kelompok9-deploy

          sudo rsync -avz --delete \
            --exclude='.env' \
            --exclude='storage' \
            --exclude='.git' \
            --exclude='.github' \
            ./ /var/www/D4RPL2C-kelompok9-deploy/

          sudo chown -R www-data:www-data /var/www/D4RPL2C-kelompok9-deploy
          sudo chmod -R 755 /var/www/D4RPL2C-kelompok9-deploy/storage
          sudo chmod -R 755 /var/www/D4RPL2C-kelompok9-deploy/bootstrap/cache

          cd /var/www/D4RPL2C-kelompok9-deploy
          sudo -u www-data composer install --optimize-autoloader --no-dev
          sudo -u www-data php artisan config:cache
          sudo -u www-data php artisan route:cache
          sudo -u www-data php artisan view:cache
          sudo -u www-data php artisan migrate --force

          # Cleanup (optional)
          rm -rf ~/D4RPL2C-kelompok9-deploy
        EOF
